version: "3"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: "ManagerDb"
        environment:
            SA_PASSWORD: "ManagerDb@Password" # put the desired password here
            ACCEPT_EULA: Y
        ports:
            - "1433:1433"
        volumes:
            - "./data:/var/opt/mssql/data"
